### ISSUE TITLE
Incunabula-demo-data.ttl doesn't pass the consistency checking

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#405]
We can't have the incunabula-demo-data.ttl pass the consistency checking.
Is it expected?

We have fixed what appear to be several mistakes, but it looks like there are some more...

graphdb 8.0.3
Incunabula-demo-data.ttl 81dfe00dee95485d41ef58419c52994645eea080

**Comment by loicjaouen** [comment]
also there are two `.pie` files:
https://github.com/dhlab-basel/Knora/blob/develop/triplestores/graphdb-se/KnoraRules.pie
https://github.com/dhlab-basel/Knora/blob/develop/webapi/scripts/KnoraRules.pie

I am assuming that we should use the former.

**Comment by subotic** [comment]
> also there are two .pie files:
https://github.com/dhlab-basel/Knora/blob/develop/triplestores/graphdb-se/KnoraRules.pie
https://github.com/dhlab-basel/Knora/blob/develop/webapi/scripts/KnoraRules.pie

Yes, the one in https://github.com/dhlab-basel/Knora/blob/develop/webapi/scripts/KnoraRules.pie is the "master" version. The one in https://github.com/dhlab-basel/Knora/blob/develop/triplestores/graphdb-se/KnoraRules.pie is a copy and needs to be updated whenever the "master" has changed.

Not a very ideal setup, as it is error prone. Maybe we should remove https://github.com/dhlab-basel/Knora/blob/develop/triplestores/graphdb-se/KnoraRules.pie from the repository and simply require that the user is providing it (like the license)?

**Comment by loicjaouen** [comment]
thanks, we re-test with the master one then, and we let you know.

**Comment by loicjaouen** [comment]
incunabula still doesn't pass graphdb consistency check

**Comment by subotic** [comment]
Did you maybe try to load https://github.com/dhlab-basel/Knora/blob/develop/webapi/_test_data/all_data/incunabula-data.ttl ?

https://github.com/dhlab-basel/Knora/blob/develop/webapi/_test_data/demo_data/incunabula-demo-data.ttl should be a subset, but maybe some needed changes where not applied. Also, in our tests we use the first one, so that would explain why we didn't catch this. We should probably have a test, that tries loads all the different ``.ttl`` data files.

**Comment by tobiasschweizer** [comment]
I do not think that `incunabula-demo-data.ttl` is used anywhere a the moment (neither loaded by the ttl-loadscripts nor used in the tests).

When I try to load it, I get this message from the consistency checker:

```
org.eclipse.rdf4j.sail.SailException: java.lang.Exception: Consistency check cardinality_1_not_less_any_object_0 failed:
http://data.knora.org/0015627fe303/values/753c03c9-8e0b-4fe8-88b4-44d6b9d991d5 http://www.knora.org/ontology/knora-base#valueCreationDate _:node98

```

The following LinkValue lacks a `valueCreationDate`:

```
<http://data.knora.org/0015627fe303/values/753c03c9-8e0b-4fe8-88b4-44d6b9d991d5> a knora-base:LinkValue ;
	rdf:subject <http://data.knora.org/0015627fe303> ;
	rdf:predicate incunabula:partOf ;
	rdf:object <http://data.knora.org/b6b5ff1eb703> ;
	knora-base:valueHasRefCount 1 ;
	knora-base:isDeleted false ;
	knora-base:attachedToUser <http://data.knora.org/users/91e19f1e01> ;
	knora-base:valueHasString "4158" ;
	knora-base:hasPermissions "CR knora-base:Creator|V knora-base:UnknownUser,knora-base:KnownUser,knora-base:ProjectMember" .
```

**Comment by mrivoal** [comment]
Yes, we have fixed the errors you are mentionning, but some more remains that we didn't go through.

I just tried to upload `incunabula-data.ttl`, but I also got a message from GraphDB consistency checker:

`org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.lang.Exception: Consistency check object_class_constraint_1 failed: http://data.knora.org/047db418ae06/values/7331b94196a104 http://www.knora.org/ontology/knora-base#valueHasStandoff http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/PRuRPhPWTuSdW7ZH8Z_AoQ http://www.knora.org/ontology/knora-base#valueHasStandoff http://www.knora.org/ontology/knora-base#objectClassConstraint http://www.knora.org/ontology/knora-base#StandoffTag ----------------------------------- http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/PRuRPhPWTuSdW7ZH8Z_AoQ http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.knora.org/ontology/knora-base#StandoffTag`

Do you have the same ?

**Comment by subotic** [comment]
Yes, I justify t ran ``./graphdb-se-local-load-test-data.sh`` inside the scripts folder:

```
[scripts] ./graphdb-se-local-load-test-data.sh                                                                                                                                                                                               develop  ✱
****************************************************************************************************
* Deleting repository

12:27:45.377 [main] DEBUG info.aduna.platform.PlatformFactory - os.name = mac os x
12:27:45.379 [main] DEBUG info.aduna.platform.PlatformFactory - Detected Mac OS X platform
Connected to http://localhost:7200

Commands end with '.' at the end of a line
Type 'help.' for help
> drop knora-test
Unknown repository 'knora-test'
> exit
Disconnecting from http://localhost:7200
Bye

****************************************************************************************************
* Creating repository

Repository created.

****************************************************************************************************
* Loading test data

12:27:46.167 [main] DEBUG info.aduna.platform.PlatformFactory - os.name = mac os x
12:27:46.170 [main] DEBUG info.aduna.platform.PlatformFactory - Detected Mac OS X platform
Connected to http://localhost:7200

Commands end with '.' at the end of a line
Type 'help.' for help
> open knora-test
Opened repository 'knora-test'
knora-test> load ../../knora-ontologies/knora-base.ttl into http://www.knora.org/ontology/knora-base
Loading data...
Data has been added to the repository (5149 ms)
knora-test> load ../../knora-ontologies/knora-admin.ttl into http://www.knora.org/ontology/knora-base
Loading data...
Data has been added to the repository (95 ms)
knora-test> load ../../knora-ontologies/standoff-onto.ttl into http://www.knora.org/ontology/standoff
Loading data...
Data has been added to the repository (70 ms)
knora-test> load ../../knora-ontologies/standoff-data.ttl into http://www.knora.org/data/standoff
Loading data...
Data has been added to the repository (84 ms)
knora-test> load ../../knora-ontologies/knora-dc.ttl into http://www.knora.org/ontology/dc
Loading data...
Data has been added to the repository (66 ms)
knora-test> load ../../knora-ontologies/salsah-gui.ttl into http://www.knora.org/ontology/salsah-gui
Loading data...
Data has been added to the repository (24 ms)
knora-test> load ../_test_data/all_data/admin-data.ttl into http://www.knora.org/data/admin
Loading data...
Data has been added to the repository (70 ms)
knora-test> load ../_test_data/all_data/permissions-data.ttl into http://www.knora.org/data/permissions
Loading data...
Data has been added to the repository (34 ms)
knora-test> load ../_test_data/ontologies/incunabula-onto.ttl into http://www.knora.org/ontology/incunabula
Loading data...
Data has been added to the repository (81 ms)
knora-test> load ../_test_data/all_data/incunabula-data.ttl into http://www.knora.org/data/incunabula
Loading data...
Data has been added to the repository (52855 ms)
knora-test> load ../_test_data/ontologies/dokubib-onto.ttl into http://www.knora.org/ontology/dokubib
Loading data...
Data has been added to the repository (55 ms)
knora-test> load ../_test_data/ontologies/images-onto.ttl into http://www.knora.org/ontology/images
Loading data...
Data has been added to the repository (48 ms)
knora-test> load ../_test_data/demo_data/images-demo-data.ttl into http://www.knora.org/data/images
Loading data...
Data has been added to the repository (567 ms)
knora-test> load ../_test_data/ontologies/anything-onto.ttl into http://www.knora.org/ontology/anything
Loading data...
Data has been added to the repository (47 ms)
knora-test> load ../_test_data/all_data/anything-data.ttl into http://www.knora.org/data/anything
Loading data...
Data has been added to the repository (172 ms)
knora-test> load ../_test_data/ontologies/beol-onto.ttl into http://www.knora.org/ontology/beol
Loading data...
Data has been added to the repository (37 ms)
knora-test> load ../_test_data/all_data/beol-data.ttl into http://www.knora.org/data/beol
Loading data...
Data has been added to the repository (23 ms)
knora-test> load ../_test_data/ontologies/biblio-onto.ttl into http://www.knora.org/ontology/biblio
Loading data...
Data has been added to the repository (49 ms)
knora-test> load ../_test_data/all_data/biblio-data.ttl into http://www.knora.org/data/biblio
Loading data...
Data has been added to the repository (18 ms)
knora-test> close
Closing repository 'knora-test'...
> exit
Disconnecting from http://localhost:7200
Bye

****************************************************************************************************
* Creating Lucene index

Lucene index built.

```

**Comment by tobiasschweizer** [comment]
Are you on `develop` and have the latest commit?

It seems to complain about a violation of an object class constraint for a standoff node.

```
<http://data.knora.org/047db418ae06/values/7331b94196a104> a knora-base:TextValue ;
        knora-base:isDeleted false ;
        knora-base:attachedToUser <http://data.knora.org/users/91e19f1e01> ;
        knora-base:valueHasString """Derselbe Holzschnitt wird auf Seite c7r der lateinischen Ausgabe des Narrenschiffs verwendet.""" ;
        knora-base:valueHasOrder 0 ;
        knora-base:valueHasStandoff <http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/moUCaHalTP6MQDx86YPw0Q> , <http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/PRuRPhPWTuSdW7ZH8Z_AoQ> , <http:\
//data.knora.org/047db418ae06/values/7331b94196a104/standoff/RGHPdxY9S3GvXcUNVFS6tA> ;
        knora-base:valueHasMapping <http://data.knora.org/projects/standoff/mappings/StandardMapping> ;
        knora-base:valueCreationDate "2016-03-02T15:05:54Z"^^xsd:dateTimeStamp ;
        knora-base:hasPermissions "CR knora-base:Creator|M knora-base:ProjectMember|V knora-base:UnknownUser,knora-base:KnownUser" .

<http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/RGHPdxY9S3GvXcUNVFS6tA> a standoff:StandoffRootTag ;
        knora-base:standoffTagHasStart "0"^^xsd:int ;
        knora-base:standoffTagHasEnd "93"^^xsd:int ;
        knora-base:standoffTagHasStartIndex "0"^^xsd:integer ;
        knora-base:standoffTagHasUUID "47875e5c-04b8-4279-b90a-8c2cdf45f9b3"^^xsd:string .

<http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/PRuRPhPWTuSdW7ZH8Z_AoQ> a standoff:StandoffParagraphTag ;
        knora-base:standoffTagHasStart "0"^^xsd:int ;
        knora-base:standoffTagHasEnd "93"^^xsd:int ;
        knora-base:standoffTagHasStartIndex "1"^^xsd:integer ;
        knora-base:standoffTagHasStartParent <http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/RGHPdxY9S3GvXcUNVFS6tA> ;
        knora-base:standoffTagHasUUID "beb746c5-6467-4e18-b201-06974e95facf" .

<http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/moUCaHalTP6MQDx86YPw0Q> a knora-base:StandoffLinkTag ;
        knora-base:standoffTagHasStart "36"^^xsd:int ;
        knora-base:standoffTagHasEnd "39"^^xsd:int ;
        knora-base:standoffTagHasLink <http://data.knora.org/c9824353ae06> ;
        knora-base:standoffTagHasStartParent <http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/PRuRPhPWTuSdW7ZH8Z_AoQ> ;
        knora-base:standoffTagHasStartIndex "2"^^xsd:integer ;
        knora-base:standoffTagHasUUID "93d31a31-af8a-4fb6-ad6d-6f768260a29e" .
```

`http://data.knora.org/047db418ae06/values/7331b94196a104/standoff/PRuRPhPWTuSdW7ZH8Z_AoQ ` is a `standoff:ParagraphTag` which is a subclass of `knora-base:StandoffTag`.

Are you sure `standoff-onto.ttl` is loaded?

**Comment by benjamingeer** [comment]
@tobiasschweizer, Ivan is talking about the file in `all_data`, not the one in `demo_data`.

This issue is assigned to me and I'm working on it, so you can all go do something else now.

**Comment by tobiasschweizer** [comment]
I was talking about `incunbula-data.ttl`. I just wanted to  help.

**Comment by benjamingeer** [comment]
@tobiasschweizer Thanks for trying to help. Fixed in #407, you can review. :)

**Comment by tobiasschweizer** [comment]
Ok, I will try to do it asap. Stuck in some crazy XPath here ...

**Comment by benjamingeer** [comment]
I didn't get any errors in `_test_data/all_data/incunabula-data.ttl`, only in `_test_data/demo_data/incunabula-demo-data.ttl`.

**Comment by loicjaouen** [comment]
- I confirm that `_test_data/all_data/incunabula-data.ttl` loads fine
- but `_test_data/demo_data/incunabula-demo-data.ttl`still fails
because of missing `valueCreationDate`

**Comment by loicjaouen** [comment]
I confirm that they both loads fine using 
100b6004fb8e0f77abe38d61b40eb1dcf369b7b3
and graphdb 8.0.3
